# Render Static Site Configuration
# Place this in render.yaml at the root of your repository

services:
  # Frontend Static Site
  - type: web
    name: epictales-frontend
    env: static
    buildCommand: npm ci && npm run build:static
    staticPublishPath: ./frontend/dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    
  # Backend API Service  
  - type: web
    name: epictales-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false # Set this in Render dashboard
      - key: CORS_ORIGINS
        value: https://your-frontend-app.onrender.com,https://epictales-frontend.onrender.com
